### PR TITLE
Parse from stream

### PR DESCRIPTION
**Pull request by thecatontheflat**
https://github.com/saul/demofile/issues/19

### CODE REVIEW

**Comment by thecatontheflat** [comment]
What do you think @saul ?

**Comment by IOExceptional** [comment]
I think there's an issue here that might cause ticks to not be parsed when there's overlap between 2 chunks. 

Probably one tick every 10MB, but still data loss

It might be possible to listen to the `demofile.on('progress', () => {})`, then add some portion of the previous chunk to the next chunk in case of an "incomplete tick error"

**Comment by thecatontheflat** [comment]
> I think there's an issue here that might cause ticks to not be parsed when there's overlap between 2 chunks.
> 
> Probably one tick every 10MB, but still data loss
> 
> It might be possible to listen to the `demofile.on('progress', () => {})`, then add some portion of the previous chunk to the next chunk in case of an "incomplete tick error"

Good point. As a quick workaround I added a variable with an arbitrary tick size which will be checked against to stop the parsing, until there's more buffer available. Maybe @saul could suggest a better solution

**Comment by thecatontheflat** [comment]
@saul bump
Let me know if you need help maintaining this repository 😊

**Comment by saul** [comment]
I've implemented this in https://github.com/saul/demofile/pull/328.

**Comment by saul** [comment]
Appreciate your contribution and thanks for nudging me on this - I've finally got around to working on a 4 year old issue :)

I'll close this off and work will continue on the other linked PR.

**Pull request closed without merging**
