### PR TITLE
range error fix

### PR DESCRIPTION
**Pull request by necuk**
Hello @saul. Here is a possible solution for #11. 
I am simply ignoring the error and finish the work after it appears. Not sure if its a best way.

Demo to reproduce the bug:
de_inferno
https://www.hltv.org/matches/2311585/outlaws-vs-spraynpray-hellcase-cup-5

Thanks in advance

### CODE REVIEW

**Comment by saul** [comment]
It's worth pointing out that this demo also breaks the official demoinfogo parser, too. I'm not sure this is the right fix as it hides other bugs (such as #43). Is there any chance you could try playing this demo in the ingame client and seeing if it plays fully?

**Comment by necuk** [comment]
this could be the case because this error seems to be produced by the server-side. here is a previous discussion on the error https://github.com/saul/demofile/issues/11

some demos:
https://www.hltv.org/matches/2311763/mask-off-vs-ajax-esea-premier-season-25-north-america
https://drive.google.com/file/d/0B-wmy64XD63INl90QktkWmRublk/edit

For me personally it seems that sometimes admin changes map before round end or some other event like stopdemo or smth. But I am not 100% sure what is the real issue.

I totally understand that this might be not your lib that produces the bug but since it appears to many people I think it should be fixed.

I am using your library on a daily basis so I would be happy to produce another patch if you tell me what was the perfomance issue in ignoring these errors you mentioned in my previous pull request

**Comment by necuk** [comment]
used game client to play very [first demo](https://www.hltv.org/matches/2311585/outlaws-vs-spraynpray-hellcase-cup-5) I provided. it stopes to play around tick 350k, score 13-8, without printing anything to console. ingame demogui shows there are more than 400k ticks in demo

**Comment by necuk** [comment]
[esea auto generated demo](https://www.hltv.org/matches/2311763/mask-off-vs-ajax-esea-premier-season-25-north-america)
was able to playback the whole demo. it stops right after the last frag in a game was made.

**Comment by necuk** [comment]
[seems to be matchmaking](https://drive.google.com/file/d/0B-wmy64XD63INl90QktkWmRublk/edit)
shows 145k in total but drops around 95k ticks. same as the first one I provided

even if its completely server-sided or valve-sided error... it seems to occure on a regular basis

**Comment by saul** [comment]
Are there any log messages in the console when it drops you back to the main menu?

**Comment by necuk** [comment]
nothing if you set developer to 0 like I used yesterday

today I tried developer 1. one of the corrupt demos provided some output in red color few rounds before crash, however the other ones didnt [gist](https://gist.github.com/necuk/222220eea62a127698523e253ce748ba)

random fact: I noticed that at the end of a demo playback it always unloads sounds that exactly match the list from gist I provided. it says like "sound1, succesfully unloaded" etc

Also all of the demos provide the following message (in white, so its like a regular output not error):

```
Demo playback finished ( 80.9 seconds, 8241 render frames, 101.82 fps).
```

**Comment by saul** [comment]
Fixed in #54

**Pull request closed without merging**
