### PR TITLE
TypeScript Migration

### LINKED ISSUE #56: TypeScript typings
The module would be easier to manage with TypeScript if there were a typings file. `@types/demofile`, or `demo.d.ts` typings definition file for the module.

### PR DESCRIPTION
**Pull request by saul**
Fixes #56 

**Todo**:

- [ ] Performance test
- [x] Document new features (e.g. 'tempent' event, Networkable)
- [x] Document API changes (e.g. usermessage event names, string table entry lengths)
- [x] Update package.json scripts (e.g. regenerate sendtabletypes.ts and eventtypes.ts)
- [x] Fix auto-generated documentation
- [x] Integrate tslint

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Woah, this looks amazing, @saul. Nice work!

I've tested it a little with a couple of the different scripts I have, and it all is working great.

**Comment by zoidbergwill** [comment]
Re: tslint

All errors:

<details>
<pre>
quotemark                       : 7434
interface-name                  : 674
class-name                      : 413
prefer-const                    : 202
no-var-keyword                  : 141
no-empty-interface              : 140
object-literal-key-quotes       : 133
no-bitwise                      : 85
member-access                   : 83
object-literal-sort-keys        : 75
semicolon                       : 66
max-line-length                 : 61
arrow-parens                    : 58
ordered-imports                 : 53
no-console                      : 51
trailing-comma                  : 37
triple-equals                   : 30
adjacent-overload-signatures    : 30
curly                           : 21
space-before-function-paren     : 16
member-ordering                 : 15
no-string-throw                 : 14
unified-signatures              : 10
variable-name                   : 10
array-type                      : 8
comment-format                  : 5
only-arrow-functions            : 4
no-consecutive-blank-lines      : 2
eofline                         : 1
max-classes-per-file            : 1
interface-over-type-literal     : 1
no-shadowed-variable            : 1
no-trailing-whitespace          : 1
</pre>
</details>


The important ones that aren't auto-fixable, and we might want to ignore:
<details>
<pre>
interface-name                  : 675
class-name                      : 413
no-empty-interface              : 140
no-bitwise                      : 85
object-literal-sort-keys        : 75
max-line-length                 : 60
no-console                      : 51
triple-equals                   : 30
adjacent-overload-signatures    : 30
variable-name                   : 10
unified-signatures              : 10
only-arrow-functions            : 4
max-classes-per-file            : 1
</pre>
</details>

Though maybe some of the TODOs we can move to separate issues and do after this is merged, but before the next release?

Side note: What if we did something like merge this into a 0.5-dev branch, and then later merged this into master, allowing people to test it out, while we polish it up, but keeping 0.4 the default for now? Though that would increase the overhead of maintaining this project on you, and that isn't reasonable to ask of someone.

**Comment by zoidbergwill** [comment]
Would it be worth making another repo that included this project as a submodule and another submodule with some example demos, similar to [this repo](https://github.com/markus-wa/demoinfocs-golang) ?

Though having benchmarks that live in this repo and we run as part of CI could be awesome too.

**Comment by saul** [comment]
Thanks @zoidbergwill - I've just pushed some commits which add tslint and fix all the errors. I want to get the remaining TODOs done, as they're just around documentation. The reason I want to run a performance test is because I think I've made it ~15% faster :)

**Pull request merged**
